'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioBasculita
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Conexion", [Namespace]:="http://schemas.datacontract.org/2004/07/wcfBascula"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Conexion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CaracterABuscarField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CaracterDeEjecucionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumCaracteresField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PosicionInicialField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuertoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CaracterABuscar() As String
            Get
                Return Me.CaracterABuscarField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CaracterABuscarField, value) <> true) Then
                    Me.CaracterABuscarField = value
                    Me.RaisePropertyChanged("CaracterABuscar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CaracterDeEjecucion() As String
            Get
                Return Me.CaracterDeEjecucionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CaracterDeEjecucionField, value) <> true) Then
                    Me.CaracterDeEjecucionField = value
                    Me.RaisePropertyChanged("CaracterDeEjecucion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IP() As String
            Get
                Return Me.IPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPField, value) <> true) Then
                    Me.IPField = value
                    Me.RaisePropertyChanged("IP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumCaracteres() As Integer
            Get
                Return Me.NumCaracteresField
            End Get
            Set
                If (Me.NumCaracteresField.Equals(value) <> true) Then
                    Me.NumCaracteresField = value
                    Me.RaisePropertyChanged("NumCaracteres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PosicionInicial() As Integer
            Get
                Return Me.PosicionInicialField
            End Get
            Set
                If (Me.PosicionInicialField.Equals(value) <> true) Then
                    Me.PosicionInicialField = value
                    Me.RaisePropertyChanged("PosicionInicial")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puerto() As String
            Get
                Return Me.PuertoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PuertoField, value) <> true) Then
                    Me.PuertoField = value
                    Me.RaisePropertyChanged("Puerto")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioBasculita.ILeerEthernet")>  _
    Public Interface ILeerEthernet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILeerEthernet/ObtenerLectura", ReplyAction:="http://tempuri.org/ILeerEthernet/ObtenerLecturaResponse")>  _
        Function ObtenerLectura(ByVal DatosConexion As ServicioBasculita.Conexion) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILeerEthernetChannel
        Inherits ServicioBasculita.ILeerEthernet, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LeerEthernetClient
        Inherits System.ServiceModel.ClientBase(Of ServicioBasculita.ILeerEthernet)
        Implements ServicioBasculita.ILeerEthernet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerLectura(ByVal DatosConexion As ServicioBasculita.Conexion) As String Implements ServicioBasculita.ILeerEthernet.ObtenerLectura
            Return MyBase.Channel.ObtenerLectura(DatosConexion)
        End Function
    End Class
End Namespace
